"""AI Integration module — M4 deliverable (Phase 2, Week 2).

Orchestrates the data flow:
  M2 (observations) → M5 (inference) → M1 (QUBO patch) + M3 (Dashboard payload)

Provides `run_ai_prediction_pipeline()` to tie these components together.
"""

from __future__ import annotations

import json
from pathlib import Path

from q_rescue.ai.predictor import build_dashboard_payload, build_qubo_patch, predict_scenario
from q_rescue.simulation.exporters import export_hydro_enriched_scenario
from q_rescue.simulation.generator import DisasterScenario


def run_ai_prediction_pipeline(
    scenario: DisasterScenario,
    hydro_params: dict,
    model_dir: Path,
    output_dir: Path | None = None,
) -> tuple[list[dict], dict, dict]:
    """Orchestrate the AI prediction flow for a scenario.

    1. Extract observations from the scenario (using M2's CSV exporter logic internally).
    2. Run XGBoost inference (M5) to get predictions.
    3. Generate QUBO patch (for M1) and Dashboard payload (for M3).
    4. Save artifacts to output_dir if provided.

    Args:
        scenario: The disaster scenario generated by M2.
        hydro_params: Configuration dict for hydro features (not actively used in current logic, passed for signature).
        model_dir: Path to the M5 XGBoost models directory.
        output_dir: Optional path to save JSON outputs (ai_predictions, qubo_ai_patch, dashboard_prediction_payload).

    Returns:
        A tuple of (predictions, qubo_patch, dashboard_payload).
    """
    scenario_id = scenario.name.lower().replace(" ", "_")
    timestamp_utc = "2026-03-14T08:30:00Z"

    # 1. Prepare observations dicts (bypassing CSV writing for in-memory flow)
    observations = []
    for i in scenario.incidents:
        hf = getattr(i, "hydro_features", {})
        obs = {
            "observation_id": f"OBS_{scenario_id}_{i.id}",
            "incident_id": i.id,
            "scenario_id": scenario_id,
            "timestamp_utc": timestamp_utc,
            **hf,
        }
        observations.append(obs)

    # 2. Run inference
    predictions = predict_scenario(scenario_id, observations, model_dir)

    # 3. Build artifacts
    qubo_patch = build_qubo_patch(predictions, scenario_id)
    dashboard_payload = build_dashboard_payload(predictions, scenario)

    # Populate ai_prediction field on each incident for the HydroEnrichedIncident format (schema §2.3)
    # We create a mapping of incident ID to prediction
    pred_map = {p["incident_id"]: p for p in predictions}
    for i in scenario.incidents:
        if i.id in pred_map:
            # We are modifying the live object, similar to how hydro_features were attached.
            # While object.__setattr__ is fragile on frozen dataclasses, we follow the pattern
            # established by M2 in scenarios.py for consistency.
            object.__setattr__(i, "ai_prediction", pred_map[i.id])

    # 4. Save to output dir if requested
    if output_dir:
        output_dir.mkdir(parents=True, exist_ok=True)

        with (output_dir / "ai_predictions.json").open("w", encoding="utf-8") as f:
            json.dump(predictions, f, indent=2)

        with (output_dir / "qubo_ai_patch.json").open("w", encoding="utf-8") as f:
            json.dump(qubo_patch, f, indent=2)

        with (output_dir / "dashboard_prediction_payload.json").open("w", encoding="utf-8") as f:
            json.dump(dashboard_payload, f, indent=2)

        export_hydro_enriched_scenario(
            scenario, output_dir / "hydro_enriched_scenario.json", hydro_params
        )

    return predictions, qubo_patch, dashboard_payload
